<?php
/**
 * Created by PhpStorm.
 * User: julio
 * Date: 3/3/17
 * Time: 2:30 PM
 */

namespace Drupal\mymodule\Entity;


use Drupal\Core\Config\Entity\ConfigEntityListBuilder;
use Drupal\Core\Entity\EntityInterface;

class SiteAnnouncementListBuilder extends ConfigEntityListBuilder{
  public function buildHeader() {
    return parent::buildHeader(); // TODO: Change the autogenerated stub
  }

  public function buildRow(EntityInterface $entity) {
    return parent::buildRow($entity); // TODO: Change the autogenerated stub
  }


}